# Generated by Django 6.0.5 on 2026-05-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodApp',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('ItemName', models.CharField(max_length=100)),
                ('Amount', models.FloatField()),
            ],
        ),
    ]
